version: '3.7'

services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf:/etc/nginx/conf.d
    restart: always
    networks:
      - app_network

  gitea:
    container_name: gitea
    image: gitea/gitea:latest
    restart: always
    env_file:
      - ./.env.gitea
    volumes:
      - ./gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:2222"
    networks:
      - app_network
    depends_on:
      - gitea_db

  gitea_db:
    container_name: gitea_db
    image: postgres:9.6
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=gitea
    expose:
      - 5432
    volumes:
      - ./gitea/db:/var/lib/postgresql/data
    networks:
      - app_network

  minio:
    container_name: minio
    image: minio/minio
    restart: always
    volumes:
      - ./minio:/data
    ports:
      - "9001:9000"
    environment:
      - MINIO_ACCESS_KEY=familyshare
      - MINIO_SECRET_KEY=familyshare
    command: server /data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - app_network

  teedy:
    container_name: teedy
    image: jdreinhardt/teedy:latest
    restart: always
    environment:
      MAX_HEAP_SIZE: "1024m"
    ports:
      - "4000:8080"
    volumes:
      - ./teedy:/data
    networks:
      - app_network

  freeradius:
    container_name: freeradius
    image: freeradius/freeradius-server:latest
    restart: always
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
    volumes:
      - ./freeradius/clients.conf:/etc/raddb/clients.conf
      - ./freeradius/authorize:/etc/raddb/mods-config/files/authorize
    networks:
      - app_network

  ebooks:
    container_name: ebooks
    image: onigoetz/comicsreader
    restart: always
    ports:
      - "4001:8080"
    volumes:
      - ./books:/comics
    networks:
      - app_network

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@domain.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - 8080:8080
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

